name: www:test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./www

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node@14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Formatting
      run: npm run format:check
    - name: Linting
      run: npm run lint
    - name: Unit tests
      run: npm test
